version: '3.5'
services:
    app:
        build: .
        ports:
            - 1000:80
        volumes:
            - .:/var/www/html
    mysql:
        image: mariadb
        ports:
            - 1001:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: schedule
        volumes:
            - mariadata:/var/lib/mysql
    adminer:
        image: adminer
        ports:
            - 1002:8080
volumes:
    mariadata:

